Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "apache"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.name = "apache"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision/install-apache.yml"
    ansible.become = true
    ansible.tags = ['apache']
  end

  config.vm.network "private_network", ip: "192.168.107.20"
  config.vm.network "forwarded_port", host: 80, guest: 80, autocorrect: true
end
