Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "centos-docker"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.name = "centos-docker"
  end

  config.vm.provision "docker" do |d|
    d.pull_images "tomcat"
    d.run "tomcat", args: "-d -p 8081:8080"
  end

  config.vm.network "private_network", ip: "192.168.107.30"
  config.vm.network "forwarded_port", host: 8082, guest: 8081, autocorrect: true
end
