require "vagrant-digitalocean"

Vagrant.configure("2") do |config|
  config.vm.box = "digital_ocean"
  config.vm.hostname = "cursovagrant"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.provider "digital_ocean" do |provider|
    provider.client_id = ENV['DIGITAL_OCEAN_CLIENT_ID']
    provider.token = ENV['DIGITAL_OCEAN_TOKEN']
    provider.ssh_key_name = ENV['DIGITAL_OCEAN_SSH_KEY_NAME']
    provider.ca_path = "/usr/local/etc/openssl/cert.pem"
    provider.image = "ubuntu-14-04-x64"
    provider.region = "nyc1"
    provider.size = "512mb"
  end
end
