require "vagrant-aws"

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.hostname = "cursovagrant"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.provider "aws" do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.keypair_name = ENV['AWS_KEYPAIR_NAME']
    aws.region = "eu-west-1"
    aws.ami = "ami-08660f1c6fb6b01e7"
    aws.instance_type = "t2.micro"
    aws.security_groups = ["default"]
    override.ssh.username = "ubuntu"
  end
end
