Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.provider "docker" do |d|
      d.image = "nginx"
    end
  end

  config.vm.define "consul" do |consul|
    consul.vm.provider "docker" do |d|
      d.image = "consul"
    end
  end
end
